# [START block-extension.configuration]
api_version = "2023-10"

[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "issue-tracker-block"
type = "ui_extension"
[[extensions.targeting]]
module = "./src/BlockExtension.jsx"
# The target used here must match the target used in the module file (./src/BlockExtension.jsx)
target = "admin.product-details.block.render"
# [END block-extension.configuration]

# Valid extension targets:
# - admin.customer-details.block.render
# - admin.order-details.block.render
# - admin.product-details.block.render
