# [START print-action-extension.configuration]
api_version = "2025-01"

[[extensions]]
name = "admin-print"
handle = "admin-print"
type = "ui_extension"

# Only 1 target can be specified for each admin print action extension
[[extensions.targeting]]
module = "./src/PrintActionExtension.jsx"
# The target used here must match the target used in the module file (./src/PrintActionExtension.tsx)
target = "admin.order-details.print-action.render"

# [END print-action-extension.configuration]
